-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgidXXcWy3oLUPfyIm
PyXIwfGa45uiiDriKujUZ7bSq0WgCgYIKoZIzj0DAQehRANCAAS4WdMT2e0SJEHx
Zq2TnRoFy6KDkA3iYeY98C3Rdy1MxJQJelZomrvA8zZJjrUJYpTrWaEYvU/GNFsb
KRa1Jlgh
-----END PRIVATE KEY-----